// DBAWORK gRPC 契约 —— Go 网关 (客户端) <-> Python 数据库运行时 (服务端)
// 生成方式见 scripts/gen_proto.ps1（Go）与 py-backend/tools/gen_proto.py（Python）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: dbawork.proto

package dbaworkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_dbawork_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{0}
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_dbawork_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Result) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// 服务器隧道 (SSH for Linux / WinRM for Windows)
type ServerTunnel struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TunnelType string                 `protobuf:"bytes,1,opt,name=tunnel_type,json=tunnelType,proto3" json:"tunnel_type,omitempty"` // none/ssh/winrm
	Host       string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port       int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"` // ssh=22, winrm=5985(http)/5986(https)
	User       string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Password   string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	// SSH 专用
	PrivateKey    string `protobuf:"bytes,6,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"` // 私钥内容或绝对路径
	KeyPassphrase string `protobuf:"bytes,7,opt,name=key_passphrase,json=keyPassphrase,proto3" json:"key_passphrase,omitempty"`
	// WinRM 专用
	AuthScheme    string `protobuf:"bytes,8,opt,name=auth_scheme,json=authScheme,proto3" json:"auth_scheme,omitempty"` // basic/ntlm/kerberos
	Transport     string `protobuf:"bytes,9,opt,name=transport,proto3" json:"transport,omitempty"`                     // http/https
	UseSsl        bool   `protobuf:"varint,10,opt,name=use_ssl,json=useSsl,proto3" json:"use_ssl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTunnel) Reset() {
	*x = ServerTunnel{}
	mi := &file_dbawork_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTunnel) ProtoMessage() {}

func (x *ServerTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTunnel.ProtoReflect.Descriptor instead.
func (*ServerTunnel) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{2}
}

func (x *ServerTunnel) GetTunnelType() string {
	if x != nil {
		return x.TunnelType
	}
	return ""
}

func (x *ServerTunnel) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServerTunnel) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerTunnel) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ServerTunnel) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ServerTunnel) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *ServerTunnel) GetKeyPassphrase() string {
	if x != nil {
		return x.KeyPassphrase
	}
	return ""
}

func (x *ServerTunnel) GetAuthScheme() string {
	if x != nil {
		return x.AuthScheme
	}
	return ""
}

func (x *ServerTunnel) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ServerTunnel) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

type DataSourceConn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DbType        string                 `protobuf:"bytes,2,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	DbName        string                 `protobuf:"bytes,5,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,8,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tunnel        *ServerTunnel          `protobuf:"bytes,9,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceConn) Reset() {
	*x = DataSourceConn{}
	mi := &file_dbawork_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceConn) ProtoMessage() {}

func (x *DataSourceConn) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceConn.ProtoReflect.Descriptor instead.
func (*DataSourceConn) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{3}
}

func (x *DataSourceConn) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataSourceConn) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *DataSourceConn) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DataSourceConn) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DataSourceConn) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *DataSourceConn) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DataSourceConn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DataSourceConn) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *DataSourceConn) GetTunnel() *ServerTunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type TestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	DbVersion     string                 `protobuf:"bytes,3,opt,name=db_version,json=dbVersion,proto3" json:"db_version,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	TestedAt      string                 `protobuf:"bytes,5,opt,name=tested_at,json=testedAt,proto3" json:"tested_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	mi := &file_dbawork_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{4}
}

func (x *TestResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TestResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TestResult) GetDbVersion() string {
	if x != nil {
		return x.DbVersion
	}
	return ""
}

func (x *TestResult) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *TestResult) GetTestedAt() string {
	if x != nil {
		return x.TestedAt
	}
	return ""
}

type DsIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DsIdRequest) Reset() {
	*x = DsIdRequest{}
	mi := &file_dbawork_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DsIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DsIdRequest) ProtoMessage() {}

func (x *DsIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DsIdRequest.ProtoReflect.Descriptor instead.
func (*DsIdRequest) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{5}
}

func (x *DsIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DbTypeInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	NameZh          string                 `protobuf:"bytes,2,opt,name=name_zh,json=nameZh,proto3" json:"name_zh,omitempty"`
	NameEn          string                 `protobuf:"bytes,3,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	DriverClassHint string                 `protobuf:"bytes,4,opt,name=driver_class_hint,json=driverClassHint,proto3" json:"driver_class_hint,omitempty"`
	IsJdbc          bool                   `protobuf:"varint,5,opt,name=is_jdbc,json=isJdbc,proto3" json:"is_jdbc,omitempty"`
	Order           int32                  `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	IsCustom        bool                   `protobuf:"varint,7,opt,name=is_custom,json=isCustom,proto3" json:"is_custom,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DbTypeInfo) Reset() {
	*x = DbTypeInfo{}
	mi := &file_dbawork_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbTypeInfo) ProtoMessage() {}

func (x *DbTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbTypeInfo.ProtoReflect.Descriptor instead.
func (*DbTypeInfo) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{6}
}

func (x *DbTypeInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DbTypeInfo) GetNameZh() string {
	if x != nil {
		return x.NameZh
	}
	return ""
}

func (x *DbTypeInfo) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *DbTypeInfo) GetDriverClassHint() string {
	if x != nil {
		return x.DriverClassHint
	}
	return ""
}

func (x *DbTypeInfo) GetIsJdbc() bool {
	if x != nil {
		return x.IsJdbc
	}
	return false
}

func (x *DbTypeInfo) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *DbTypeInfo) GetIsCustom() bool {
	if x != nil {
		return x.IsCustom
	}
	return false
}

type ListDbTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeHidden bool                   `protobuf:"varint,1,opt,name=include_hidden,json=includeHidden,proto3" json:"include_hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDbTypesRequest) Reset() {
	*x = ListDbTypesRequest{}
	mi := &file_dbawork_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDbTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDbTypesRequest) ProtoMessage() {}

func (x *ListDbTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDbTypesRequest.ProtoReflect.Descriptor instead.
func (*ListDbTypesRequest) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{7}
}

func (x *ListDbTypesRequest) GetIncludeHidden() bool {
	if x != nil {
		return x.IncludeHidden
	}
	return false
}

type ListDbTypesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*DbTypeInfo          `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDbTypesReply) Reset() {
	*x = ListDbTypesReply{}
	mi := &file_dbawork_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDbTypesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDbTypesReply) ProtoMessage() {}

func (x *ListDbTypesReply) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDbTypesReply.ProtoReflect.Descriptor instead.
func (*ListDbTypesReply) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{8}
}

func (x *ListDbTypesReply) GetTypes() []*DbTypeInfo {
	if x != nil {
		return x.Types
	}
	return nil
}

type DriverStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DbType           string                 `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	DriverKind       string                 `protobuf:"bytes,2,opt,name=driver_kind,json=driverKind,proto3" json:"driver_kind,omitempty"` // python | jdbc
	PackageName      string                 `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Installed        bool                   `protobuf:"varint,4,opt,name=installed,proto3" json:"installed,omitempty"`
	InstalledVersion string                 `protobuf:"bytes,5,opt,name=installed_version,json=installedVersion,proto3" json:"installed_version,omitempty"`
	Note             string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DriverStatus) Reset() {
	*x = DriverStatus{}
	mi := &file_dbawork_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverStatus) ProtoMessage() {}

func (x *DriverStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverStatus.ProtoReflect.Descriptor instead.
func (*DriverStatus) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{9}
}

func (x *DriverStatus) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *DriverStatus) GetDriverKind() string {
	if x != nil {
		return x.DriverKind
	}
	return ""
}

func (x *DriverStatus) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *DriverStatus) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *DriverStatus) GetInstalledVersion() string {
	if x != nil {
		return x.InstalledVersion
	}
	return ""
}

func (x *DriverStatus) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DetectAllReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*DriverStatus        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectAllReply) Reset() {
	*x = DetectAllReply{}
	mi := &file_dbawork_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectAllReply) ProtoMessage() {}

func (x *DetectAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectAllReply.ProtoReflect.Descriptor instead.
func (*DetectAllReply) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{10}
}

func (x *DetectAllReply) GetStatuses() []*DriverStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type DetectOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbType        string                 `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectOneRequest) Reset() {
	*x = DetectOneRequest{}
	mi := &file_dbawork_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectOneRequest) ProtoMessage() {}

func (x *DetectOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectOneRequest.ProtoReflect.Descriptor instead.
func (*DetectOneRequest) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{11}
}

func (x *DetectOneRequest) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

type InstallDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbType        string                 `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	DriverKind    string                 `protobuf:"bytes,2,opt,name=driver_kind,json=driverKind,proto3" json:"driver_kind,omitempty"`
	PackageName   string                 `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallDriverRequest) Reset() {
	*x = InstallDriverRequest{}
	mi := &file_dbawork_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallDriverRequest) ProtoMessage() {}

func (x *InstallDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallDriverRequest.ProtoReflect.Descriptor instead.
func (*InstallDriverRequest) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{12}
}

func (x *InstallDriverRequest) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *InstallDriverRequest) GetDriverKind() string {
	if x != nil {
		return x.DriverKind
	}
	return ""
}

func (x *InstallDriverRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *InstallDriverRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UninstallDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbType        string                 `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	DriverKind    string                 `protobuf:"bytes,2,opt,name=driver_kind,json=driverKind,proto3" json:"driver_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallDriverRequest) Reset() {
	*x = UninstallDriverRequest{}
	mi := &file_dbawork_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallDriverRequest) ProtoMessage() {}

func (x *UninstallDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallDriverRequest.ProtoReflect.Descriptor instead.
func (*UninstallDriverRequest) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{13}
}

func (x *UninstallDriverRequest) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *UninstallDriverRequest) GetDriverKind() string {
	if x != nil {
		return x.DriverKind
	}
	return ""
}

type UploadJarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbType        string                 `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	DriverClass   string                 `protobuf:"bytes,3,opt,name=driver_class,json=driverClass,proto3" json:"driver_class,omitempty"`
	JarFilename   string                 `protobuf:"bytes,4,opt,name=jar_filename,json=jarFilename,proto3" json:"jar_filename,omitempty"`
	JarBytes      []byte                 `protobuf:"bytes,5,opt,name=jar_bytes,json=jarBytes,proto3" json:"jar_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadJarRequest) Reset() {
	*x = UploadJarRequest{}
	mi := &file_dbawork_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadJarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadJarRequest) ProtoMessage() {}

func (x *UploadJarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadJarRequest.ProtoReflect.Descriptor instead.
func (*UploadJarRequest) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{14}
}

func (x *UploadJarRequest) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *UploadJarRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UploadJarRequest) GetDriverClass() string {
	if x != nil {
		return x.DriverClass
	}
	return ""
}

func (x *UploadJarRequest) GetJarFilename() string {
	if x != nil {
		return x.JarFilename
	}
	return ""
}

func (x *UploadJarRequest) GetJarBytes() []byte {
	if x != nil {
		return x.JarBytes
	}
	return nil
}

type UploadJarReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	JarPath       string                 `protobuf:"bytes,2,opt,name=jar_path,json=jarPath,proto3" json:"jar_path,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadJarReply) Reset() {
	*x = UploadJarReply{}
	mi := &file_dbawork_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadJarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadJarReply) ProtoMessage() {}

func (x *UploadJarReply) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadJarReply.ProtoReflect.Descriptor instead.
func (*UploadJarReply) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{15}
}

func (x *UploadJarReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UploadJarReply) GetJarPath() string {
	if x != nil {
		return x.JarPath
	}
	return ""
}

func (x *UploadJarReply) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadJarReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteJarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JarPath       string                 `protobuf:"bytes,1,opt,name=jar_path,json=jarPath,proto3" json:"jar_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJarRequest) Reset() {
	*x = DeleteJarRequest{}
	mi := &file_dbawork_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJarRequest) ProtoMessage() {}

func (x *DeleteJarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJarRequest.ProtoReflect.Descriptor instead.
func (*DeleteJarRequest) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteJarRequest) GetJarPath() string {
	if x != nil {
		return x.JarPath
	}
	return ""
}

type ActivateDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbType        string                 `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	DriverId      int32                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateDriverRequest) Reset() {
	*x = ActivateDriverRequest{}
	mi := &file_dbawork_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateDriverRequest) ProtoMessage() {}

func (x *ActivateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbawork_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateDriverRequest.ProtoReflect.Descriptor instead.
func (*ActivateDriverRequest) Descriptor() ([]byte, []int) {
	return file_dbawork_proto_rawDescGZIP(), []int{17}
}

func (x *ActivateDriverRequest) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *ActivateDriverRequest) GetDriverId() int32 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

var File_dbawork_proto protoreflect.FileDescriptor

const file_dbawork_proto_rawDesc = "" +
	"\n" +
	"\rdbawork.proto\x12\n" +
	"dbawork.v1\"\a\n" +
	"\x05Empty\"J\n" +
	"\x06Result\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xa7\x02\n" +
	"\fServerTunnel\x12\x1f\n" +
	"\vtunnel_type\x18\x01 \x01(\tR\n" +
	"tunnelType\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1f\n" +
	"\vprivate_key\x18\x06 \x01(\tR\n" +
	"privateKey\x12%\n" +
	"\x0ekey_passphrase\x18\a \x01(\tR\rkeyPassphrase\x12\x1f\n" +
	"\vauth_scheme\x18\b \x01(\tR\n" +
	"authScheme\x12\x1c\n" +
	"\ttransport\x18\t \x01(\tR\ttransport\x12\x17\n" +
	"\ause_ssl\x18\n" +
	" \x01(\bR\x06useSsl\"\xdb\x02\n" +
	"\x0eDataSourceConn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\adb_type\x18\x02 \x01(\tR\x06dbType\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x17\n" +
	"\adb_name\x18\x05 \x01(\tR\x06dbName\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12;\n" +
	"\x05extra\x18\b \x03(\v2%.dbawork.v1.DataSourceConn.ExtraEntryR\x05extra\x120\n" +
	"\x06tunnel\x18\t \x01(\v2\x18.dbawork.v1.ServerTunnelR\x06tunnel\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\n" +
	"TestResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"db_version\x18\x03 \x01(\tR\tdbVersion\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x05R\tlatencyMs\x12\x1b\n" +
	"\ttested_at\x18\x05 \x01(\tR\btestedAt\"\x1d\n" +
	"\vDsIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xc8\x01\n" +
	"\n" +
	"DbTypeInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x17\n" +
	"\aname_zh\x18\x02 \x01(\tR\x06nameZh\x12\x17\n" +
	"\aname_en\x18\x03 \x01(\tR\x06nameEn\x12*\n" +
	"\x11driver_class_hint\x18\x04 \x01(\tR\x0fdriverClassHint\x12\x17\n" +
	"\ais_jdbc\x18\x05 \x01(\bR\x06isJdbc\x12\x14\n" +
	"\x05order\x18\x06 \x01(\x05R\x05order\x12\x1b\n" +
	"\tis_custom\x18\a \x01(\bR\bisCustom\";\n" +
	"\x12ListDbTypesRequest\x12%\n" +
	"\x0einclude_hidden\x18\x01 \x01(\bR\rincludeHidden\"@\n" +
	"\x10ListDbTypesReply\x12,\n" +
	"\x05types\x18\x01 \x03(\v2\x16.dbawork.v1.DbTypeInfoR\x05types\"\xca\x01\n" +
	"\fDriverStatus\x12\x17\n" +
	"\adb_type\x18\x01 \x01(\tR\x06dbType\x12\x1f\n" +
	"\vdriver_kind\x18\x02 \x01(\tR\n" +
	"driverKind\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12\x1c\n" +
	"\tinstalled\x18\x04 \x01(\bR\tinstalled\x12+\n" +
	"\x11installed_version\x18\x05 \x01(\tR\x10installedVersion\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\"F\n" +
	"\x0eDetectAllReply\x124\n" +
	"\bstatuses\x18\x01 \x03(\v2\x18.dbawork.v1.DriverStatusR\bstatuses\"+\n" +
	"\x10DetectOneRequest\x12\x17\n" +
	"\adb_type\x18\x01 \x01(\tR\x06dbType\"\x8d\x01\n" +
	"\x14InstallDriverRequest\x12\x17\n" +
	"\adb_type\x18\x01 \x01(\tR\x06dbType\x12\x1f\n" +
	"\vdriver_kind\x18\x02 \x01(\tR\n" +
	"driverKind\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"R\n" +
	"\x16UninstallDriverRequest\x12\x17\n" +
	"\adb_type\x18\x01 \x01(\tR\x06dbType\x12\x1f\n" +
	"\vdriver_kind\x18\x02 \x01(\tR\n" +
	"driverKind\"\xa8\x01\n" +
	"\x10UploadJarRequest\x12\x17\n" +
	"\adb_type\x18\x01 \x01(\tR\x06dbType\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fdriver_class\x18\x03 \x01(\tR\vdriverClass\x12!\n" +
	"\fjar_filename\x18\x04 \x01(\tR\vjarFilename\x12\x1b\n" +
	"\tjar_bytes\x18\x05 \x01(\fR\bjarBytes\"r\n" +
	"\x0eUploadJarReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x19\n" +
	"\bjar_path\x18\x02 \x01(\tR\ajarPath\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"-\n" +
	"\x10DeleteJarRequest\x12\x19\n" +
	"\bjar_path\x18\x01 \x01(\tR\ajarPath\"M\n" +
	"\x15ActivateDriverRequest\x12\x17\n" +
	"\adb_type\x18\x01 \x01(\tR\x06dbType\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x05R\bdriverId2\xa0\x01\n" +
	"\x11ConnectionService\x12D\n" +
	"\x0eTestConnection\x12\x1a.dbawork.v1.DataSourceConn\x1a\x16.dbawork.v1.TestResult\x12E\n" +
	"\x12TestConnectionById\x12\x17.dbawork.v1.DsIdRequest\x1a\x16.dbawork.v1.TestResult2\xbe\x04\n" +
	"\rDriverService\x12K\n" +
	"\vListDbTypes\x12\x1e.dbawork.v1.ListDbTypesRequest\x1a\x1c.dbawork.v1.ListDbTypesReply\x12:\n" +
	"\tDetectAll\x12\x11.dbawork.v1.Empty\x1a\x1a.dbawork.v1.DetectAllReply\x12C\n" +
	"\tDetectOne\x12\x1c.dbawork.v1.DetectOneRequest\x1a\x18.dbawork.v1.DriverStatus\x12E\n" +
	"\rInstallDriver\x12 .dbawork.v1.InstallDriverRequest\x1a\x12.dbawork.v1.Result\x12I\n" +
	"\x0fUninstallDriver\x12\".dbawork.v1.UninstallDriverRequest\x1a\x12.dbawork.v1.Result\x12E\n" +
	"\tUploadJar\x12\x1c.dbawork.v1.UploadJarRequest\x1a\x1a.dbawork.v1.UploadJarReply\x12=\n" +
	"\tDeleteJar\x12\x1c.dbawork.v1.DeleteJarRequest\x1a\x12.dbawork.v1.Result\x12G\n" +
	"\x0eActivateDriver\x12!.dbawork.v1.ActivateDriverRequest\x1a\x12.dbawork.v1.ResultB#Z!dbawork/proto/dbaworkv1;dbaworkv1b\x06proto3"

var (
	file_dbawork_proto_rawDescOnce sync.Once
	file_dbawork_proto_rawDescData []byte
)

func file_dbawork_proto_rawDescGZIP() []byte {
	file_dbawork_proto_rawDescOnce.Do(func() {
		file_dbawork_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dbawork_proto_rawDesc), len(file_dbawork_proto_rawDesc)))
	})
	return file_dbawork_proto_rawDescData
}

var file_dbawork_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_dbawork_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: dbawork.v1.Empty
	(*Result)(nil),                 // 1: dbawork.v1.Result
	(*ServerTunnel)(nil),           // 2: dbawork.v1.ServerTunnel
	(*DataSourceConn)(nil),         // 3: dbawork.v1.DataSourceConn
	(*TestResult)(nil),             // 4: dbawork.v1.TestResult
	(*DsIdRequest)(nil),            // 5: dbawork.v1.DsIdRequest
	(*DbTypeInfo)(nil),             // 6: dbawork.v1.DbTypeInfo
	(*ListDbTypesRequest)(nil),     // 7: dbawork.v1.ListDbTypesRequest
	(*ListDbTypesReply)(nil),       // 8: dbawork.v1.ListDbTypesReply
	(*DriverStatus)(nil),           // 9: dbawork.v1.DriverStatus
	(*DetectAllReply)(nil),         // 10: dbawork.v1.DetectAllReply
	(*DetectOneRequest)(nil),       // 11: dbawork.v1.DetectOneRequest
	(*InstallDriverRequest)(nil),   // 12: dbawork.v1.InstallDriverRequest
	(*UninstallDriverRequest)(nil), // 13: dbawork.v1.UninstallDriverRequest
	(*UploadJarRequest)(nil),       // 14: dbawork.v1.UploadJarRequest
	(*UploadJarReply)(nil),         // 15: dbawork.v1.UploadJarReply
	(*DeleteJarRequest)(nil),       // 16: dbawork.v1.DeleteJarRequest
	(*ActivateDriverRequest)(nil),  // 17: dbawork.v1.ActivateDriverRequest
	nil,                            // 18: dbawork.v1.DataSourceConn.ExtraEntry
}
var file_dbawork_proto_depIdxs = []int32{
	18, // 0: dbawork.v1.DataSourceConn.extra:type_name -> dbawork.v1.DataSourceConn.ExtraEntry
	2,  // 1: dbawork.v1.DataSourceConn.tunnel:type_name -> dbawork.v1.ServerTunnel
	6,  // 2: dbawork.v1.ListDbTypesReply.types:type_name -> dbawork.v1.DbTypeInfo
	9,  // 3: dbawork.v1.DetectAllReply.statuses:type_name -> dbawork.v1.DriverStatus
	3,  // 4: dbawork.v1.ConnectionService.TestConnection:input_type -> dbawork.v1.DataSourceConn
	5,  // 5: dbawork.v1.ConnectionService.TestConnectionById:input_type -> dbawork.v1.DsIdRequest
	7,  // 6: dbawork.v1.DriverService.ListDbTypes:input_type -> dbawork.v1.ListDbTypesRequest
	0,  // 7: dbawork.v1.DriverService.DetectAll:input_type -> dbawork.v1.Empty
	11, // 8: dbawork.v1.DriverService.DetectOne:input_type -> dbawork.v1.DetectOneRequest
	12, // 9: dbawork.v1.DriverService.InstallDriver:input_type -> dbawork.v1.InstallDriverRequest
	13, // 10: dbawork.v1.DriverService.UninstallDriver:input_type -> dbawork.v1.UninstallDriverRequest
	14, // 11: dbawork.v1.DriverService.UploadJar:input_type -> dbawork.v1.UploadJarRequest
	16, // 12: dbawork.v1.DriverService.DeleteJar:input_type -> dbawork.v1.DeleteJarRequest
	17, // 13: dbawork.v1.DriverService.ActivateDriver:input_type -> dbawork.v1.ActivateDriverRequest
	4,  // 14: dbawork.v1.ConnectionService.TestConnection:output_type -> dbawork.v1.TestResult
	4,  // 15: dbawork.v1.ConnectionService.TestConnectionById:output_type -> dbawork.v1.TestResult
	8,  // 16: dbawork.v1.DriverService.ListDbTypes:output_type -> dbawork.v1.ListDbTypesReply
	10, // 17: dbawork.v1.DriverService.DetectAll:output_type -> dbawork.v1.DetectAllReply
	9,  // 18: dbawork.v1.DriverService.DetectOne:output_type -> dbawork.v1.DriverStatus
	1,  // 19: dbawork.v1.DriverService.InstallDriver:output_type -> dbawork.v1.Result
	1,  // 20: dbawork.v1.DriverService.UninstallDriver:output_type -> dbawork.v1.Result
	15, // 21: dbawork.v1.DriverService.UploadJar:output_type -> dbawork.v1.UploadJarReply
	1,  // 22: dbawork.v1.DriverService.DeleteJar:output_type -> dbawork.v1.Result
	1,  // 23: dbawork.v1.DriverService.ActivateDriver:output_type -> dbawork.v1.Result
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_dbawork_proto_init() }
func file_dbawork_proto_init() {
	if File_dbawork_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dbawork_proto_rawDesc), len(file_dbawork_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dbawork_proto_goTypes,
		DependencyIndexes: file_dbawork_proto_depIdxs,
		MessageInfos:      file_dbawork_proto_msgTypes,
	}.Build()
	File_dbawork_proto = out.File
	file_dbawork_proto_goTypes = nil
	file_dbawork_proto_depIdxs = nil
}
