// DBAWORK gRPC 契约 —— Go 网关 (客户端) <-> Python 数据库运行时 (服务端)
// 生成方式见 scripts/gen_proto.ps1（Go）与 py-backend/tools/gen_proto.py（Python）

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: dbawork.proto

package dbaworkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectionService_TestConnection_FullMethodName     = "/dbawork.v1.ConnectionService/TestConnection"
	ConnectionService_TestConnectionById_FullMethodName = "/dbawork.v1.ConnectionService/TestConnectionById"
)

// ConnectionServiceClient is the client API for ConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectionServiceClient interface {
	TestConnection(ctx context.Context, in *DataSourceConn, opts ...grpc.CallOption) (*TestResult, error)
	TestConnectionById(ctx context.Context, in *DsIdRequest, opts ...grpc.CallOption) (*TestResult, error)
}

type connectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionServiceClient(cc grpc.ClientConnInterface) ConnectionServiceClient {
	return &connectionServiceClient{cc}
}

func (c *connectionServiceClient) TestConnection(ctx context.Context, in *DataSourceConn, opts ...grpc.CallOption) (*TestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResult)
	err := c.cc.Invoke(ctx, ConnectionService_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) TestConnectionById(ctx context.Context, in *DsIdRequest, opts ...grpc.CallOption) (*TestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResult)
	err := c.cc.Invoke(ctx, ConnectionService_TestConnectionById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServiceServer is the server API for ConnectionService service.
// All implementations must embed UnimplementedConnectionServiceServer
// for forward compatibility.
type ConnectionServiceServer interface {
	TestConnection(context.Context, *DataSourceConn) (*TestResult, error)
	TestConnectionById(context.Context, *DsIdRequest) (*TestResult, error)
	mustEmbedUnimplementedConnectionServiceServer()
}

// UnimplementedConnectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectionServiceServer struct{}

func (UnimplementedConnectionServiceServer) TestConnection(context.Context, *DataSourceConn) (*TestResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedConnectionServiceServer) TestConnectionById(context.Context, *DsIdRequest) (*TestResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnectionById not implemented")
}
func (UnimplementedConnectionServiceServer) mustEmbedUnimplementedConnectionServiceServer() {}
func (UnimplementedConnectionServiceServer) testEmbeddedByValue()                           {}

// UnsafeConnectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionServiceServer will
// result in compilation errors.
type UnsafeConnectionServiceServer interface {
	mustEmbedUnimplementedConnectionServiceServer()
}

func RegisterConnectionServiceServer(s grpc.ServiceRegistrar, srv ConnectionServiceServer) {
	// If the following call panics, it indicates UnimplementedConnectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectionService_ServiceDesc, srv)
}

func _ConnectionService_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataSourceConn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).TestConnection(ctx, req.(*DataSourceConn))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_TestConnectionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DsIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).TestConnectionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_TestConnectionById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).TestConnectionById(ctx, req.(*DsIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectionService_ServiceDesc is the grpc.ServiceDesc for ConnectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbawork.v1.ConnectionService",
	HandlerType: (*ConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConnection",
			Handler:    _ConnectionService_TestConnection_Handler,
		},
		{
			MethodName: "TestConnectionById",
			Handler:    _ConnectionService_TestConnectionById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbawork.proto",
}

const (
	DriverService_ListDbTypes_FullMethodName     = "/dbawork.v1.DriverService/ListDbTypes"
	DriverService_DetectAll_FullMethodName       = "/dbawork.v1.DriverService/DetectAll"
	DriverService_DetectOne_FullMethodName       = "/dbawork.v1.DriverService/DetectOne"
	DriverService_InstallDriver_FullMethodName   = "/dbawork.v1.DriverService/InstallDriver"
	DriverService_UninstallDriver_FullMethodName = "/dbawork.v1.DriverService/UninstallDriver"
	DriverService_UploadJar_FullMethodName       = "/dbawork.v1.DriverService/UploadJar"
	DriverService_DeleteJar_FullMethodName       = "/dbawork.v1.DriverService/DeleteJar"
	DriverService_ActivateDriver_FullMethodName  = "/dbawork.v1.DriverService/ActivateDriver"
)

// DriverServiceClient is the client API for DriverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverServiceClient interface {
	ListDbTypes(ctx context.Context, in *ListDbTypesRequest, opts ...grpc.CallOption) (*ListDbTypesReply, error)
	DetectAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DetectAllReply, error)
	DetectOne(ctx context.Context, in *DetectOneRequest, opts ...grpc.CallOption) (*DriverStatus, error)
	InstallDriver(ctx context.Context, in *InstallDriverRequest, opts ...grpc.CallOption) (*Result, error)
	UninstallDriver(ctx context.Context, in *UninstallDriverRequest, opts ...grpc.CallOption) (*Result, error)
	UploadJar(ctx context.Context, in *UploadJarRequest, opts ...grpc.CallOption) (*UploadJarReply, error)
	DeleteJar(ctx context.Context, in *DeleteJarRequest, opts ...grpc.CallOption) (*Result, error)
	ActivateDriver(ctx context.Context, in *ActivateDriverRequest, opts ...grpc.CallOption) (*Result, error)
}

type driverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverServiceClient(cc grpc.ClientConnInterface) DriverServiceClient {
	return &driverServiceClient{cc}
}

func (c *driverServiceClient) ListDbTypes(ctx context.Context, in *ListDbTypesRequest, opts ...grpc.CallOption) (*ListDbTypesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDbTypesReply)
	err := c.cc.Invoke(ctx, DriverService_ListDbTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) DetectAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DetectAllReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectAllReply)
	err := c.cc.Invoke(ctx, DriverService_DetectAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) DetectOne(ctx context.Context, in *DetectOneRequest, opts ...grpc.CallOption) (*DriverStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverStatus)
	err := c.cc.Invoke(ctx, DriverService_DetectOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) InstallDriver(ctx context.Context, in *InstallDriverRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, DriverService_InstallDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UninstallDriver(ctx context.Context, in *UninstallDriverRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, DriverService_UninstallDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UploadJar(ctx context.Context, in *UploadJarRequest, opts ...grpc.CallOption) (*UploadJarReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadJarReply)
	err := c.cc.Invoke(ctx, DriverService_UploadJar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) DeleteJar(ctx context.Context, in *DeleteJarRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, DriverService_DeleteJar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ActivateDriver(ctx context.Context, in *ActivateDriverRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, DriverService_ActivateDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServiceServer is the server API for DriverService service.
// All implementations must embed UnimplementedDriverServiceServer
// for forward compatibility.
type DriverServiceServer interface {
	ListDbTypes(context.Context, *ListDbTypesRequest) (*ListDbTypesReply, error)
	DetectAll(context.Context, *Empty) (*DetectAllReply, error)
	DetectOne(context.Context, *DetectOneRequest) (*DriverStatus, error)
	InstallDriver(context.Context, *InstallDriverRequest) (*Result, error)
	UninstallDriver(context.Context, *UninstallDriverRequest) (*Result, error)
	UploadJar(context.Context, *UploadJarRequest) (*UploadJarReply, error)
	DeleteJar(context.Context, *DeleteJarRequest) (*Result, error)
	ActivateDriver(context.Context, *ActivateDriverRequest) (*Result, error)
	mustEmbedUnimplementedDriverServiceServer()
}

// UnimplementedDriverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServiceServer struct{}

func (UnimplementedDriverServiceServer) ListDbTypes(context.Context, *ListDbTypesRequest) (*ListDbTypesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDbTypes not implemented")
}
func (UnimplementedDriverServiceServer) DetectAll(context.Context, *Empty) (*DetectAllReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectAll not implemented")
}
func (UnimplementedDriverServiceServer) DetectOne(context.Context, *DetectOneRequest) (*DriverStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectOne not implemented")
}
func (UnimplementedDriverServiceServer) InstallDriver(context.Context, *InstallDriverRequest) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallDriver not implemented")
}
func (UnimplementedDriverServiceServer) UninstallDriver(context.Context, *UninstallDriverRequest) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method UninstallDriver not implemented")
}
func (UnimplementedDriverServiceServer) UploadJar(context.Context, *UploadJarRequest) (*UploadJarReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadJar not implemented")
}
func (UnimplementedDriverServiceServer) DeleteJar(context.Context, *DeleteJarRequest) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteJar not implemented")
}
func (UnimplementedDriverServiceServer) ActivateDriver(context.Context, *ActivateDriverRequest) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateDriver not implemented")
}
func (UnimplementedDriverServiceServer) mustEmbedUnimplementedDriverServiceServer() {}
func (UnimplementedDriverServiceServer) testEmbeddedByValue()                       {}

// UnsafeDriverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServiceServer will
// result in compilation errors.
type UnsafeDriverServiceServer interface {
	mustEmbedUnimplementedDriverServiceServer()
}

func RegisterDriverServiceServer(s grpc.ServiceRegistrar, srv DriverServiceServer) {
	// If the following call panics, it indicates UnimplementedDriverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverService_ServiceDesc, srv)
}

func _DriverService_ListDbTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDbTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ListDbTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ListDbTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ListDbTypes(ctx, req.(*ListDbTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_DetectAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).DetectAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_DetectAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).DetectAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_DetectOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).DetectOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_DetectOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).DetectOne(ctx, req.(*DetectOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_InstallDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).InstallDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_InstallDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).InstallDriver(ctx, req.(*InstallDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UninstallDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UninstallDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UninstallDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UninstallDriver(ctx, req.(*UninstallDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UploadJar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadJarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UploadJar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UploadJar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UploadJar(ctx, req.(*UploadJarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_DeleteJar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).DeleteJar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_DeleteJar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).DeleteJar(ctx, req.(*DeleteJarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ActivateDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ActivateDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ActivateDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ActivateDriver(ctx, req.(*ActivateDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverService_ServiceDesc is the grpc.ServiceDesc for DriverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbawork.v1.DriverService",
	HandlerType: (*DriverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDbTypes",
			Handler:    _DriverService_ListDbTypes_Handler,
		},
		{
			MethodName: "DetectAll",
			Handler:    _DriverService_DetectAll_Handler,
		},
		{
			MethodName: "DetectOne",
			Handler:    _DriverService_DetectOne_Handler,
		},
		{
			MethodName: "InstallDriver",
			Handler:    _DriverService_InstallDriver_Handler,
		},
		{
			MethodName: "UninstallDriver",
			Handler:    _DriverService_UninstallDriver_Handler,
		},
		{
			MethodName: "UploadJar",
			Handler:    _DriverService_UploadJar_Handler,
		},
		{
			MethodName: "DeleteJar",
			Handler:    _DriverService_DeleteJar_Handler,
		},
		{
			MethodName: "ActivateDriver",
			Handler:    _DriverService_ActivateDriver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbawork.proto",
}
